// ==UserScript==
// @name           subreddit_blocker
// @description    Hides all posts from a subreddit by name (not case sensitive) or by regex.
// @author         khlam
// @match          http://*.reddit.com/*
// @match          https://*.reddit.com/*
// @version        0.0
// ==/UserScript==

const regex = [/porn/, /meme/, /anime/, /fucking/, /circlejerk/, /twitter/, /ask/, /comedy/, /tiktok/]

const blacklisted_subs = [ // not case sensitive
    "MadeMeSmile",
    "funny",
    "Damnthatsinteresting",
    "mildlyinfuriating",
    "Futurology",
    "gaming",
    "aww",
    "pics",
    "PublicFreakout",
    "HermanCainAward",
    "insaneparents",
    "NoStupidQuestions",
    "antiwork",
    "technology",
    "nextfuckinglevel",
    "CryptoCurrency",
    "wallstreetbets",
    "Superstonk",
    "todayilearned",
    "CasualUK",
    "interestingasfuck",
    "teenagers",
    "Unexpected",
    "MurderedByWords",
    "JusticeServed",
    "ContagiousLaughter",
    "oddlyterrifying",
    "meirl",
    "SquaredCircle",
    "HolUp",
    "Tinder",
    "tumblr",
    "TaylorSwift",
    "PoliticalHumor",
    "NatureIsFuckingLit",
    "TrueOffMyChest",
    "vexillology",
    "MaliciousCompliance",
    "Whatcouldgowrong",
    "facepalm",
    "shittymoviedetails",
    "moviedetails",
    "iamatotalpieceofshit",
    "sports",
    "baseball",
    "nba",
    "coolguides",
    "Cringetopia",
    "blursedimages",
    "TwoXChromosomes",
    "ToiletPaperUSA",
    "mildlyinteresting",
    "marvelstudios",
    "Genshin_Impact",
    "CozyPlaces",
    "dataisbeautiful",
    "technicallythetruth",
    "TikTokCringe",
    "awfuleverything",
    "AdviceAnimals",
    "greentext",
    "IllegallySmolCats",
    "AnimalsBeingBros",
    "CrappyDesign",
    "canada",
    "confidentlyincorrect",
    "cats",
    "IdiotsInCars",
    "me_irl",
    "shitposting",
    "WinStupidPrizes",
    "gifsthatkeepongiving",
    "trashy",
    "oddlysatisfying",
    "AbruptChaos",
    "Eyebleach",
    "Wellthatsucks",
    "ShitPostCrusaders",
    "atheism",
    "bi_irl",
    "neoliberal",
    "nonononoyes",
    "amcstock",
    "stocks",
    "FuckYouKaren",
    "whenthe",
    "rarepuppers",
    "rareinsults",
    "AnimalsBeingDerps",
    "WatchPeopleDieInside",
    "SubredditDrama",
    "HumansBeingBros",
    "OutOfTheLoop",
    "KidsAreFuckingStupid",
    "BeAmazed",
    "PlayStationPlus",
    "AnimalCrossing",
    "BestofRedditorUpdates",
    "WitchesVsPatriarchy",
    "SelfAwarewolves",
    "OldSchoolCool",
    "Showerthoughts",
    "tifu",
    "sadcringe",
    "explainlikeimfive",
    "WorkReform",
    "LifeProTips",
    "LateStageCapitalism",
    "byebyejob",
    "WhatsWrongWithYourDog",
    "LeopardsAteMyFace",
    "ABoringDystopia",
    "Instagramreality",
    "Zoomies",
    "maybemaybemaybe",
    "assholedesign",
    "woahdude",
    "hmm",
    "UNBGBBIIVCHIDCTIICBG",
    "natureismetal",
    "ThatsInsane",
    "WhatsWrongWithYourCat",
    "AbsoluteUnits",
    "therewasanattempt",
    "unpopularopinion",
    "Catswithjobs",
    "perfectlycutscreams",
    "JoeRogan",
    "YouShouldKnow",
    "gatekeeping",
    "LivestreamFail",
    "Bitcoin",
    "MurderedByAOC",
    "BrandNewSentence",
    "ThatLookedExpensive",
    "UpliftingNews",
    "worldnewsvideo",
    "clevercomebacks",
    "instant_regret",
    "FunnyandSad",
    "onguardforthee",
    "blursed_videos",
    "Perfectfit",
    "bonehurtingjuice",
    "SuddenlyGay",
    "im14andthisisdeep",
]

let blacklisted_subs_lower = blacklisted_subs.map(e => { return e.toLowerCase() }) // all blacklisted subreddits to lowercase

let all_threads = document.querySelectorAll("[data-subreddit]")

all_threads.forEach(thread => {
    let this_sub = thread.getAttribute('data-subreddit').toLowerCase() // post's subreddit to lowercase

    // if subreddit is in blacklist or if subreddit matches regex then hide it
    if ((blacklisted_subs_lower.includes(this_sub) === true) || regex.some(function(r) { return r.test(this_sub)}) === true) { 
        console.log("HIDING", thread)
        //thread.innerHTML = `Content from ${this_sub} hidden.`
        thread.style.display = "none"
    }
})